### PR TITLE
Create AzureAnalyticsE2E.json

### PR DESCRIPTION
**Pull request by AKrishna1087192**

### CODE REVIEW

**Comment by AKrishna1087192** [comment]
added new AzureSynapseE2e

**Review by AKrishna1087192 — COMMENTED** [review]
Added AzureSynapseE2e

**Comment by AKrishna1087192** [comment]
Added E2e synapse workspace

**Review by v-vhimabindu — APPROVED** [review]

**Comment by v-vhimabindu** [comment]
reviewed

**Review by v-vhimabindu — APPROVED** [review]

**Pull request merged**
